### PR TITLE
Fix missing `EventPayload.id`

### LINKED ISSUE #423: [BUG] `id` field is missing from the type definition of `EventPayload`
**Describe the bug**
The optional `id` field for idempotent event processing is not defined in the `EventPayload` interface and therefore provides no type checking / editor integration.

see: https://github.com/inngest/inngest-js/blob/main/packages/inngest/src/types.ts#L305

docs: https://www.inngest.com/docs/reference/events/send#inngest-send-event-payload-event-payload-promise

### PR DESCRIPTION
**Pull request by jpwilliams**
## Summary

Fixes #423, where `id` is missing in types when attempting to send an event using `inngest.send()` or `step.sendEvent()`.

## Checklist

- [ ] ~~Added a [docs PR](https://github.com/inngest/website) that references this PR~~ N/A Bug fix
- [x] Added unit/integration tests
- [x] Added changesets if applicable

## Related

- Fixes #423

### CODE REVIEW

File: packages/inngest/src/types.ts [hunk 1]
```diff
@@ -304,7 +304,19 @@ export type AnyHandler = Handler<any, any, any, any>;
  */
 export interface EventPayload {
   /**
-   * A unique identifier for the event
+   * A unique id used to idempotently ingest a given event payload once (i.e.
+   * deduplication).
+   *
+   * Set this when sending events to ensure that the event is only processed
+   * once; if an event with the same ID is sent again, it will be ignored.
```
Comment (tonyhb) [inline packages/inngest/src/types.ts:311]:
```suggestion
   * A unique id used to idempotently process a given event payload.
   *
   * Set this when sending events to ensure that the event is only processed
   * once; if an event with the same ID is sent again, it will not invoke functions.
```

**Review by tonyhb — APPROVED** [review]

File: packages/inngest/src/types.ts (hunk 1 above)
Comment (tonyhb) [reply packages/inngest/src/types.ts:311]: The aim here is to make it clear that funciton runs are handled idempotently.  Handling idempotency at the event level is too much work for the events API, which handles tens of thousands of events per second 😬

Comment (jpwilliams) [reply packages/inngest/src/types.ts:311]: (ty - committed this)
